apiVersion: v1
kind: Service
metadata:
  name: {{ template "avorion.fullname" . }}-udp
  labels:
    app: {{ template "avorion.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ template "avorion.fullname" . }}
spec:
  type: {{ .Values.avorionServer.serviceType }}
  ports:
  {{- if eq "LoadBalancer" .Values.avorionServer.serviceType }}
  - name: avorion-udp-1
    port: 27000
    targetPort: avorion-udp-1
    protocol: UDP
  - name: avorion-udp-2
    port: 27003
    targetPort: avorion-udp-2
    protocol: UDP
  - name: avorion-udp-3
    port: 27020
    targetPort: avorion-udp-3
    protocol: UDP
  - name: avorion-udp-4
    port: 27021
    targetPort: avorion-udp-4
    protocol: UDP
  {{- else }}
  - name: avorion-1
    port: {{ .Values.avorionServer.serverPort | int }}
    targetPort: avorion-1
    nodePort: {{ .Values.avorionServer.serverPort | int }}
    protocol: UDP
  {{- end }}
  selector:
    app: {{ template "avorion.fullname" . }}
