apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "valheim.fullname" . }}-configmap
data:
  server.ini: |
  {{- range $key, $value := .Values.settingsINI }}
    {{ $key }}={{ $value }}
  {{- end }}
